# Goals of this Activity


## 1. Implement convolution
Given an n,m RGB image as a numpy array and a k x k x 3 convolution filter. Implement the
convolution operation with ‘same’ padding without using higher level functions like conv2d from tensorflow, or convolve from numpy. 

- [Theano Convulation Arithmetic](http://deeplearning.net/software/theano/tutorial/conv_arithmetic.html)
- [Machine learning guru](http://machinelearninguru.com/computer_vision/basics/convolution/image_convolution_1.html)
- [Kernel Image Processing Wiki](https://en.wikipedia.org/wiki/Kernel_(image_processing))
- [CNN Standford](http://cs231n.github.io/convolutional-networks/#pool) 



In [1]:
import numpy as np 

def isSquare (m): return all (len (row) == len (m) for row in m)

def padding(image, kernel):
    '''
    Pad the matrix with zero all room 
    '''
    if isSquare(kernel):
        pad = int((len(kernel) - 1) / 2)

        # padding the image
        width_im = len(im[0])
        zero = [0] * (width_im + 2 * pad)
        pad_im = [zero] * pad

        pad_lst = [0] * pad

        for row in im:
            tmp = [0] * pad
            tmp.extend(row)
            tmp.extend([0] * pad)
            pad_im.append(tmp)

        pad_im.extend([zero] * pad)
        pad_im = np.array(pad_im)
    return pad_im

def reverting_ker(kernel):
    '''
    revert the kernel matrix 
    '''
    lst = []
    for row in kernel[::-1]:
        lst.append(row[::-1])
    return(np.array(lst))

def helper(a,b):
    '''
    a and b must be the same size
    return the convolution result for a sub matrix 
    '''
    return sum([i * j for i, j in zip(a.flatten(), b.flatten())])

def sub(mat, kernel):
    '''
    generate the result of the convolution with the kernel filter 
    k is the size of the square sub matrix
    
    '''
    k = len(kernel)
    m = len(mat)
    n = len(mat[0])
    
    i = 0
    j = 0
    res = []
    final = []
    
    while i + k <= m:
        while j + k <= n:
            tmp = mat[i:i+k, j:j+k]
            res.append(helper(tmp, kernel))
            j += 1
            
        final.append(res)
        res = []
        j = 0
        i += 1
    
    final = np.array(final)
    return final

def convolve(image, kernel):
    
    pad_im = padding(image, kernel)
    kernel = reverting_ker(kernel)
    
    return sub(pad_im, kernel)
    


im = np.array([[1, 2, 0, 0], [5, 3, 0, 4], [0, 0, 0, 7], [9, 3, 0, 0]])
kernel = np.array([[1,1,1],[1,1,0],[1,0,0]])

result = convolve(im, kernel)
print(result)

[[11 10  7  4]
 [10  3 11 11]
 [15 12 14  7]
 [12  3  7  0]]


In [2]:
import numpy as np
from scipy.signal import convolve2d 
res = convolve2d(im, kernel,mode='same')
print(res)


[[11 10  7  4]
 [10  3 11 11]
 [15 12 14  7]
 [12  3  7  0]]


In [3]:
# Check if the result is the same as the one generated with an high level function
np.testing.assert_array_equal(res, result)

## 2. Implement max_pool 
Given a grayscale image as a numpy array. We are also given a k by k max pooling filter with a stride of 1. Implement the max_pool operation without using higher level functions like block_reduce.

In [13]:
import numpy as np 

def max_pool(image, k):
    
    m = len(image)
    n = len(image[0])
    
    i = 0
    j = 0
    res = []
    final = []
    
    while i + k <= m:
        while j + k <= n:
            tmp = image[i:i+k, j:j+k]
            res.append(np.max(tmp))
            j += k
            
        final.append(res)
        res = []
        j = 0
        i += k
    
    final = np.array(final)
    return final

im = np.array([[1, 2, 0, 0], [5, 3, 0, 4], [0, 0, 0, 7], [9, 3, 0, 0]])
k = 2



In [14]:
print(im)

[[1 2 0 0]
 [5 3 0 4]
 [0 0 0 7]
 [9 3 0 0]]


In [15]:
result = max_pool(im, k)
print(result)

[[5 4]
 [9 7]]


In [16]:
import skimage.measure
res = skimage.measure.block_reduce(im, (k,k), np.max)
print(res)

[[5 4]
 [9 7]]


In [17]:
np.testing.assert_array_equal(res, result)