In [2]:

import numpy as np

[Backpropagation](https://hmkcode.github.io/ai/backpropagation-step-by-step/)

In [137]:

# input + bias
input_d = [1,0]
output = 1
bias = 1

input_d.extend([bias])

i = np.array(input_d)
i

# Forward Pass
print("\nForward Pass\n")
# initial weight
print('initial weight \n')
w = np.array([[0.5, 0.5],[0.5, 0.5],[0.3, 0.3]])
# weight for output layer
print(w)
w_o = np.array([[0.5],[0.5],[0.3]])
print(w_o)


h = np.matmul(i,w)
print(h)

# adding bias to hidden layer 
d = h.tolist()
d.extend([bias])
d = np.array(d)

# output
print('\noutput after forward pass')
o = np.matmul(d, w_o)[0]
print(o)

# error 
print('\nerror')
error = 0.5 * (o - output)**2
print(error)


# Backward Pass
l_r = 0.05 #learning rate
delta = o - output
print("\ndelta")
print(delta)

print("\nbackward pass\n")
print('output weight after hidden layer')
w_o_b =  np.transpose(w_o) - l_r * delta * d
w_o_b = np.transpose(w_o_b)
print(w_o_b)

tmp = w_o.tolist()[:2]
z = np.array(tmp).T
w_h_b = w - l_r * delta * np.matmul(i[np.newaxis].T, z)
print('\ninput weight')
print(w_h_b)


e = np.matmul(i, w_h_b)
e = e.tolist()
e.extend([bias])
e = np.array(e)
print('\noutput after backward pass')
f = np.matmul(e, w_o_b)[0]
print(f)




Forward Pass

initial weight 

[[0.5 0.5]
 [0.5 0.5]
 [0.3 0.3]]
[[0.5]
 [0.5]
 [0.3]]
[0.8 0.8]

output after forward pass
1.1

error
0.005000000000000009

delta
0.10000000000000009

backward pass

output weight after hidden layer
[[0.496]
 [0.496]
 [0.295]]

input weight
[[0.4975 0.4975]
 [0.5    0.5   ]
 [0.2975 0.2975]]

output after backward pass
1.08364


In [138]:
# input + bias
input_d = [1,1]
output = 0
bias = 1

input_d.extend([bias])

i = np.array(input_d)
i

# Forward Pass
print("\nForward Pass\n")
# initial weight
print('initial weight \n')
w = np.array([[0.5, 0.5],[0.5, 0.5],[0.3, 0.3]])
# weight for output layer
print(w)
w_o = np.array([[0.5],[0.5],[0.3]])
print(w_o)


h = np.matmul(i,w)
print(h)

# adding bias to hidden layer 
d = h.tolist()
d.extend([bias])
d = np.array(d)

# output
print('\noutput after forward pass')
o = np.matmul(d, w_o)[0]
print(o)

# error 
print('\nerror')
error = 0.5 * (o - output)**2
print(error)


# Backward Pass
l_r = 0.05 #learning rate
delta = o - output
print("\ndelta")
print(delta)

print("\nbackward pass\n")
print('output weight after hidden layer')
w_o_b =  np.transpose(w_o) - l_r * delta * d
w_o_b = np.transpose(w_o_b)
print(w_o_b)

tmp = w_o.tolist()[:2]
z = np.array(tmp).T
w_h_b = w - l_r * delta * np.matmul(i[np.newaxis].T, z)
print('\ninput weight')
print(w_h_b)


e = np.matmul(i, w_h_b)
e = e.tolist()
e.extend([bias])
e = np.array(e)
print('\noutput after backward pass')
f = np.matmul(e, w_o_b)[0]
print(f)


Forward Pass

initial weight 

[[0.5 0.5]
 [0.5 0.5]
 [0.3 0.3]]
[[0.5]
 [0.5]
 [0.3]]
[1.3 1.3]

output after forward pass
1.6

error
1.2800000000000002

delta
1.6

backward pass

output weight after hidden layer
[[0.396]
 [0.396]
 [0.22 ]]

input weight
[[0.46 0.46]
 [0.46 0.46]
 [0.26 0.26]]

output after backward pass
1.1545599999999998
