# Lesson 6 Practice Exercise

## Start


- [Assignment](https://canvas.uw.edu/courses/1260524/assignments/4656100?module_item_id=9186173)
- [LSTM Tutorial](https://adventuresinmachinelearning.com/keras-lstm-tutorial/)
- [Understand the Difference Between Return Sequences and Return States for LSTMs in Keras](https://machinelearningmastery.com/return-sequences-and-return-states-for-lstms-in-keras/)
- [MIT Deep Learning Book](https://www.deeplearningbook.org/)
- [KERAS LSTM](https://keras.io/layers/recurrent/)

In [25]:
from keras.models import Model
from keras.layers import Input, LSTM, GRU
import numpy as np

timesteps = 8
num_features = 2
num_nodes = 3

# Create some random data
data = np.random.randn(1, timesteps, num_features)
print(data)

[[[ 0.17462766 -0.92567869]
  [-0.65052345  0.10157572]
  [-0.85950322  0.24404285]
  [-1.41132314  0.46512797]
  [-1.30753876  1.59086708]
  [ 0.24468414  1.78127748]
  [-1.61193248 -0.92883158]
  [-0.28950088 -0.36427538]]]


## Q1: What do the dimensions of the data represent? E.g., what do the 1st dimension, the 2nd, and the 3rd represent here?

```np.random.randn``` return a sample from the normal distribution
with the parameters 1, timesteps, numfeatures, it return one array of timesteps rows and numfeatures columns 
This means that we will observe 2 features at each time steps

In [21]:
inputs = Input(shape=(timesteps, num_features))
rnn = LSTM(num_nodes, return_state=True)
x = rnn(inputs)

model = Model(inputs=inputs, outputs=x)
output, h, c = model.predict(data)

print("output:", output)
print("h:", h)
print("c:", c)

output: [[ 0.30340108 -0.02182508  0.01595481]]
h: [[ 0.30340108 -0.02182508  0.01595481]]
c: [[ 0.48878998 -0.04866165  0.05372298]]


## Q2: What do these "predict" return values (output, h, and c) represent? Describe what they mean.



```output``` represents the hidden state for the last time step 

```h``` represents the hidden state for the last time step 

```c``` represents the cell state for the last time step 

## Q3: What are the dimensions of output, h, and c?



the dimension of ```output``` is a vector of the same dimension as the number of nodes

the dimension of ```h``` is a vector of the same dimension as the number of nodes

the dimension of ```c``` is a vector of the same dimension as the number of nodes

## Q4: Is there any duplication among the values of (output, h, c)? If so, explain.



In this particular case, ```output``` and ```h``` are the same

## Q5: Change the LSTM to use "return_state=False" and modify the code accordingly to avoid errors. What does the LSTM return now?

In [22]:
inputs = Input(shape=(timesteps, num_features))
rnn = LSTM(num_nodes, return_state=True, return_sequences=True)
x = rnn(inputs)

model = Model(inputs=inputs, outputs=x)
output, h, c = model.predict(data)

print("output:", output)
print("h:", h)
print("c:", c)

output: [[[-0.10392016  0.00788214 -0.05634788]
  [-0.00842382 -0.02919971  0.00064112]
  [ 0.09601593 -0.03341671  0.06656042]
  [ 0.00259915 -0.00714997 -0.00404387]
  [ 0.23388243 -0.01044396  0.07503767]
  [ 0.18487996  0.01161234  0.10406002]
  [ 0.34996822  0.03541033  0.13783318]
  [ 0.07637344  0.05555646 -0.14589013]]]
h: [[ 0.07637344  0.05555646 -0.14589013]]
c: [[ 0.14130604  0.25121632 -0.22767267]]


## Q6: Now, what are the dimensions of output, h, and c?


##  Q7: What does the output variable represent now? Explain the dimensions of the returned matrix (e.g., what does the 1st dimension represent? What does the 2nd represent? The 3rd? etc.)

In [23]:
inputs = Input(shape=(timesteps, num_features))
rnn = GRU(num_nodes, return_state=True)
x = rnn(inputs)
model = Model(inputs=inputs, outputs=x)
output, h = model.predict(data)

print("o:", output)
print("h:", h)

o: [[0.12989618 0.07255637 0.48050374]]
h: [[0.12989618 0.07255637 0.48050374]]


## Q8: What happened to the variable "c"? Why does the GRU only return a tuple of 2 values as opposed to 3?



 



## Q9: What are the dimension of output and h?

## Q10: Is there any duplication between the values of output and h? If so, explain.

In [24]:
inputs = Input(shape=(timesteps, num_features))
rnn = GRU(num_nodes, return_state=True, return_sequences=True)
x = rnn(inputs)
model = Model(inputs=inputs, outputs=x)
output, h = model.predict(data)

print("o:", output)
print("h:", h)

o: [[[ 0.05947458  0.14367878 -0.0625222 ]
  [ 0.2650104  -0.5001869   0.15283206]
  [ 0.07584788 -0.50175714  0.1920328 ]
  [ 0.31399244 -0.43849233  0.20544109]
  [-0.10257311 -0.28285685  0.08623705]
  [ 0.00861287 -0.44242558  0.19347444]
  [-0.25936615 -0.22612503  0.06639826]
  [ 0.42000502  0.3223763  -0.07728104]]]
h: [[ 0.42000502  0.3223763  -0.07728104]]


## Q11: Now, what are the dimensions of output and h?



## Q12: Is there any duplication within the values of output and h? If so, explain. 